/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router"

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as IndexImport } from "./routes/index"
import { Route as StateLayoutImport } from "./routes/$state/_layout"

// Create Virtual Routes

const StateImport = createFileRoute("/$state")()
const StateLayoutIndexLazyImport = createFileRoute("/$state/_layout/")()
const StateLayoutSummaryIndexLazyImport = createFileRoute(
  "/$state/_layout/summary/",
)()
const StateLayoutRacialIndexLazyImport = createFileRoute(
  "/$state/_layout/racial/",
)()
const StateLayoutPrecinctIndexLazyImport = createFileRoute(
  "/$state/_layout/precinct/",
)()
const StateLayoutPlanIndexLazyImport = createFileRoute(
  "/$state/_layout/plan/",
)()

// Create/Update Routes

const StateRoute = StateImport.update({
  path: "/$state",
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

const StateLayoutRoute = StateLayoutImport.update({
  id: "/_layout",
  getParentRoute: () => StateRoute,
} as any)

const StateLayoutIndexLazyRoute = StateLayoutIndexLazyImport.update({
  path: "/",
  getParentRoute: () => StateLayoutRoute,
} as any).lazy(() =>
  import("./routes/$state/_layout/index.lazy").then((d) => d.Route),
)

const StateLayoutSummaryIndexLazyRoute =
  StateLayoutSummaryIndexLazyImport.update({
    path: "/summary/",
    getParentRoute: () => StateLayoutRoute,
  } as any).lazy(() =>
    import("./routes/$state/_layout/summary/index.lazy").then((d) => d.Route),
  )

const StateLayoutRacialIndexLazyRoute = StateLayoutRacialIndexLazyImport.update(
  {
    path: "/racial/",
    getParentRoute: () => StateLayoutRoute,
  } as any,
).lazy(() =>
  import("./routes/$state/_layout/racial/index.lazy").then((d) => d.Route),
)

const StateLayoutPrecinctIndexLazyRoute =
  StateLayoutPrecinctIndexLazyImport.update({
    path: "/precinct/",
    getParentRoute: () => StateLayoutRoute,
  } as any).lazy(() =>
    import("./routes/$state/_layout/precinct/index.lazy").then((d) => d.Route),
  )

const StateLayoutPlanIndexLazyRoute = StateLayoutPlanIndexLazyImport.update({
  path: "/plan/",
  getParentRoute: () => StateLayoutRoute,
} as any).lazy(() =>
  import("./routes/$state/_layout/plan/index.lazy").then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/$state": {
      preLoaderRoute: typeof StateImport
      parentRoute: typeof rootRoute
    }
    "/$state/_layout": {
      preLoaderRoute: typeof StateLayoutImport
      parentRoute: typeof StateRoute
    }
    "/$state/_layout/": {
      preLoaderRoute: typeof StateLayoutIndexLazyImport
      parentRoute: typeof StateLayoutImport
    }
    "/$state/_layout/plan/": {
      preLoaderRoute: typeof StateLayoutPlanIndexLazyImport
      parentRoute: typeof StateLayoutImport
    }
    "/$state/_layout/precinct/": {
      preLoaderRoute: typeof StateLayoutPrecinctIndexLazyImport
      parentRoute: typeof StateLayoutImport
    }
    "/$state/_layout/racial/": {
      preLoaderRoute: typeof StateLayoutRacialIndexLazyImport
      parentRoute: typeof StateLayoutImport
    }
    "/$state/_layout/summary/": {
      preLoaderRoute: typeof StateLayoutSummaryIndexLazyImport
      parentRoute: typeof StateLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  StateRoute.addChildren([
    StateLayoutRoute.addChildren([
      StateLayoutIndexLazyRoute,
      StateLayoutPlanIndexLazyRoute,
      StateLayoutPrecinctIndexLazyRoute,
      StateLayoutRacialIndexLazyRoute,
      StateLayoutSummaryIndexLazyRoute,
    ]),
  ]),
])

/* prettier-ignore-end */
